// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static java.lang.Thread.sleep;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddMedicalRecordTest {
    private static final long SLEEP_TIME = 2000;
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void addMedicalRecord() throws InterruptedException {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("div[class='ant-space css-dev-only-do-not-override-k6wk4u ant-space-horizontal ant-space-align-center'] div[class='ant-space-item']")).click();
        driver.findElement(By.id("basic_email")).sendKeys("nguyenthanhhai@gmail.com");
        driver.findElement(By.id("basic_password")).sendKeys("nguyenthanhhai@gmail.com");
        driver.findElement(By.id("basic_organization")).click();
        driver.findElement(By.cssSelector("body > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1)")).click();
        driver.findElement(By.cssSelector("button[type='submit'] span")).click();

        sleep(SLEEP_TIME);
        assertThat(driver.findElement(By.xpath("//span[contains(text(),'Quản lý yêu cầu')]")).getText(), is("Quản lý yêu cầu"));
        driver.findElement(By.xpath("//span[contains(text(),'Quản lý yêu cầu')]")).click();
        sleep(SLEEP_TIME);
        driver.findElement(By.cssSelector(".ant-table-cell:nth-child(6) .ant-dropdown-trigger")).click();
        driver.findElement(By.cssSelector("body > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(2) > span:nth-child(1) > span:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".ant-btn-primary > span")).click();
        driver.findElement(By.cssSelector(".ant-table-cell:nth-child(7) .ant-dropdown-trigger")).click();
        driver.findElement(By.cssSelector("body > div:nth-child(4) > div:nth-child(1) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > span:nth-child(1) > span:nth-child(2)")).click();
        sleep(SLEEP_TIME);
        driver.findElement(By.cssSelector("div[class='ant-dropdown css-dev-only-do-not-override-uz5yzm ant-dropdown-placement-bottomRight'] button:nth-child(2) span:nth-child(1)")).click();
        sleep(SLEEP_TIME);
        assertThat(driver.findElement(By.cssSelector("tbody tr:nth-child(1) td:nth-child(6)")).getText(), is("Đặt lịch khám"));
        assertThat(driver.findElement(By.cssSelector("tbody tr:nth-child(1) td:nth-child(7)")).getText(), is("CHỜ XỬ LÝ"));
        driver.findElement(By.cssSelector(".ant-table-row:nth-child(1) span:nth-child(2)")).click();
        sleep(SLEEP_TIME);
        driver.findElement(By.cssSelector(".ant-btn:nth-child(3) > span")).click();
        sleep(SLEEP_TIME);
        driver.findElement(By.id("basic_testName")).click();
        driver.findElement(By.id("basic_testName")).sendKeys("Xét nghiệm máu");
        driver.findElement(By.id("basic_details")).click();
        driver.findElement(By.id("basic_details")).sendKeys("Tất cả các chỉ số bình thường");
        driver.findElement(By.cssSelector(".ant-btn-dashed")).click();
        driver.findElement(By.id("basic_prescriptionDetailsList_0_medicationId")).click();
        driver.findElement(By.cssSelector(".ant-select-tree-treenode:nth-child(2) .ant-select-tree-title")).click();
        driver.findElement(By.id("basic_prescriptionDetailsList_0_quantity")).click();
        driver.findElement(By.id("basic_prescriptionDetailsList_0_quantity")).sendKeys("10");
        driver.findElement(By.id("basic_prescriptionDetailsList_0_details")).click();
        driver.findElement(By.id("basic_prescriptionDetailsList_0_details")).sendKeys("Uống 2 viên mỗi ngày");
        driver.findElement(By.cssSelector("#basic > div > .ant-btn > span")).click();
        sleep(SLEEP_TIME);
        driver.findElement(By.cssSelector(".ant-modal-footer > .ant-btn-primary > span")).click();
        sleep(SLEEP_TIME * 2);
        driver.findElement(By.cssSelector(".ant-notification-notice-success .ant-notification-notice-with-icon")).click();
        assertThat(driver.findElement(By.cssSelector(".ant-notification-notice-success .ant-notification-notice-message")).getText(), is("Thành công"));
    }
}
