PeerOrgs:
  - Name: Orderer
    Domain: orderer.healthcare.com
    Specs:
      - Hostname: orderer0.orderers-group
      - Hostname: orderer1.orderers-group
      - Hostname: orderer2.orderers-group
    Template:
      Count: 0
    Users:
      Count: 1
